'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class svstoreEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=svstoreEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property brands() As DbSet(Of brand)
    Public Overridable Property categories() As DbSet(Of category)
    Public Overridable Property products() As DbSet(Of product)

End Class
