'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class product
    Public Property id As Integer
    Public Property prodname As String
    Public Property cat_id As Nullable(Of Integer)
    Public Property brand_id As Nullable(Of Integer)
    Public Property qty As Nullable(Of Integer)
    Public Property price As Nullable(Of Decimal)

    Public Overridable Property brand As brand
    Public Overridable Property category As category

End Class
